"""Added Payment Status to the Online Order db

Revision ID: f4c6f21b9bf7
Revises: c91bd0b2689c
Create Date: 2025-05-31 14:19:35.343293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c6f21b9bf7'
down_revision = 'c91bd0b2689c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('online_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('online_order', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
